version: "3.9"

services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
