on:
  workflow_dispatch:   # manual trigger only

jobs:
  run-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    environment: Env

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run tests only
      - name: Run tests
        run: pytest -v


