on:
  push:
    paths:
      - "storage/**/*.csv"   # Trigger only when CSVs are added/modified in data/

jobs:
  run-etl:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed for committing back to repo
    environment: Env
    env: 
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
    #Postgress   
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

    steps:
      # ⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      #  Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      #  Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests 
        run: |
          pytest  -v
      # ⃣ Run ETL script
      - name: Run ETL
        run: python src/main.py
      #  Slack notification on success
      
      
      
      - name: Slack Notification Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "ETL Success: Database Sync"
          SLACK_COLOR: "good"
          SLACK_MESSAGE: "The workflow finished successfully! ✅\nView Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Slack Notification Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "ETL Failure: Database Sync"
          SLACK_COLOR: "danger"
          SLACK_MESSAGE: "The workflow failed. ❌ Please check the logs to fix the error.\nView Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
